package BaseDados;
// Generated 7/jun/2017 21:44:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private BigDecimal codigo;
     private String nome;
     private String especialidade;
     private Set encomendas = new HashSet(0);
     private Set servicos = new HashSet(0);
     private Set vendaservicoses = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(BigDecimal codigo, String nome, String especialidade) {
        this.codigo = codigo;
        this.nome = nome;
        this.especialidade = especialidade;
    }
    public Funcionario(BigDecimal codigo, String nome, String especialidade, Set encomendas, Set servicos, Set vendaservicoses) {
       this.codigo = codigo;
       this.nome = nome;
       this.especialidade = especialidade;
       this.encomendas = encomendas;
       this.servicos = servicos;
       this.vendaservicoses = vendaservicoses;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEspecialidade() {
        return this.especialidade;
    }
    
    public void setEspecialidade(String especialidade) {
        this.especialidade = especialidade;
    }
    public Set getEncomendas() {
        return this.encomendas;
    }
    
    public void setEncomendas(Set encomendas) {
        this.encomendas = encomendas;
    }
    public Set getServicos() {
        return this.servicos;
    }
    
    public void setServicos(Set servicos) {
        this.servicos = servicos;
    }
    public Set getVendaservicoses() {
        return this.vendaservicoses;
    }
    
    public void setVendaservicoses(Set vendaservicoses) {
        this.vendaservicoses = vendaservicoses;
    }




}


