package BaseDados;
// Generated 7/jun/2017 21:44:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Linhavendaprodutos generated by hbm2java
 */
public class Linhavendaprodutos  implements java.io.Serializable {


     private BigDecimal codigo;
     private Produto produto;
     private Vendaprodutos vendaprodutos;
     private BigDecimal quantidade;
     private double precounitario;
     private double precototal;

    public Linhavendaprodutos() {
    }

    public Linhavendaprodutos(BigDecimal codigo, Produto produto, Vendaprodutos vendaprodutos, BigDecimal quantidade, double precounitario, double precototal) {
       this.codigo = codigo;
       this.produto = produto;
       this.vendaprodutos = vendaprodutos;
       this.quantidade = quantidade;
       this.precounitario = precounitario;
       this.precototal = precototal;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Vendaprodutos getVendaprodutos() {
        return this.vendaprodutos;
    }
    
    public void setVendaprodutos(Vendaprodutos vendaprodutos) {
        this.vendaprodutos = vendaprodutos;
    }
    public BigDecimal getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(BigDecimal quantidade) {
        this.quantidade = quantidade;
    }
    public double getPrecounitario() {
        return this.precounitario;
    }
    
    public void setPrecounitario(double precounitario) {
        this.precounitario = precounitario;
    }
    public double getPrecototal() {
        return this.precototal;
    }
    
    public void setPrecototal(double precototal) {
        this.precototal = precototal;
    }




}


