package BaseDados;
// Generated 7/jun/2017 21:44:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Linhaencomenda generated by hbm2java
 */
public class Linhaencomenda  implements java.io.Serializable {


     private BigDecimal codigo;
     private Produto produto;
     private Encomenda encomenda;
     private BigDecimal quantidade;
     private double precounitario;
     private double precototal;

    public Linhaencomenda() {
    }

    public Linhaencomenda(BigDecimal codigo, Produto produto, Encomenda encomenda, BigDecimal quantidade, double precounitario, double precototal) {
       this.codigo = codigo;
       this.produto = produto;
       this.encomenda = encomenda;
       this.quantidade = quantidade;
       this.precounitario = precounitario;
       this.precototal = precototal;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Encomenda getEncomenda() {
        return this.encomenda;
    }
    
    public void setEncomenda(Encomenda encomenda) {
        this.encomenda = encomenda;
    }
    public BigDecimal getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(BigDecimal quantidade) {
        this.quantidade = quantidade;
    }
    public double getPrecounitario() {
        return this.precounitario;
    }
    
    public void setPrecounitario(double precounitario) {
        this.precounitario = precounitario;
    }
    public double getPrecototal() {
        return this.precototal;
    }
    
    public void setPrecototal(double precototal) {
        this.precototal = precototal;
    }




}


