package BaseDados;
// Generated 7/jun/2017 21:44:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Linhavendaservicos generated by hbm2java
 */
public class Linhavendaservicos  implements java.io.Serializable {


     private BigDecimal codigo;
     private Servico servico;
     private Vendaservicos vendaservicos;
     private BigDecimal quantidade;
     private double precounitario;
     private double precototal;

    public Linhavendaservicos() {
    }

    public Linhavendaservicos(BigDecimal codigo, Servico servico, Vendaservicos vendaservicos, BigDecimal quantidade, double precounitario, double precototal) {
       this.codigo = codigo;
       this.servico = servico;
       this.vendaservicos = vendaservicos;
       this.quantidade = quantidade;
       this.precounitario = precounitario;
       this.precototal = precototal;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Servico getServico() {
        return this.servico;
    }
    
    public void setServico(Servico servico) {
        this.servico = servico;
    }
    public Vendaservicos getVendaservicos() {
        return this.vendaservicos;
    }
    
    public void setVendaservicos(Vendaservicos vendaservicos) {
        this.vendaservicos = vendaservicos;
    }
    public BigDecimal getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(BigDecimal quantidade) {
        this.quantidade = quantidade;
    }
    public double getPrecounitario() {
        return this.precounitario;
    }
    
    public void setPrecounitario(double precounitario) {
        this.precounitario = precounitario;
    }
    public double getPrecototal() {
        return this.precototal;
    }
    
    public void setPrecototal(double precototal) {
        this.precototal = precototal;
    }




}


