package BaseDados;
// Generated 7/jun/2017 21:44:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Marcacao generated by hbm2java
 */
public class Marcacao  implements java.io.Serializable {


     private BigDecimal codigo;
     private Cliente cliente;
     private String tiposervico;
     private Date datamarcacao;

    public Marcacao() {
    }

    public Marcacao(BigDecimal codigo, Cliente cliente, String tiposervico, Date datamarcacao) {
       this.codigo = codigo;
       this.cliente = cliente;
       this.tiposervico = tiposervico;
       this.datamarcacao = datamarcacao;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getTiposervico() {
        return this.tiposervico;
    }
    
    public void setTiposervico(String tiposervico) {
        this.tiposervico = tiposervico;
    }
    public Date getDatamarcacao() {
        return this.datamarcacao;
    }
    
    public void setDatamarcacao(Date datamarcacao) {
        this.datamarcacao = datamarcacao;
    }




}


