package BaseDados;
// Generated 7/jun/2017 21:44:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private BigDecimal codigo;
     private Cliente cliente;
     private double preco;
     private String descricao;
     private BigDecimal quantidadeemstock;
     private Set linhavendaprodutoses = new HashSet(0);
     private Set linhaencomendas = new HashSet(0);

    public Produto() {
    }

	
    public Produto(BigDecimal codigo, Cliente cliente, double preco, String descricao, BigDecimal quantidadeemstock) {
        this.codigo = codigo;
        this.cliente = cliente;
        this.preco = preco;
        this.descricao = descricao;
        this.quantidadeemstock = quantidadeemstock;
    }
    public Produto(BigDecimal codigo, Cliente cliente, double preco, String descricao, BigDecimal quantidadeemstock, Set linhavendaprodutoses, Set linhaencomendas) {
       this.codigo = codigo;
       this.cliente = cliente;
       this.preco = preco;
       this.descricao = descricao;
       this.quantidadeemstock = quantidadeemstock;
       this.linhavendaprodutoses = linhavendaprodutoses;
       this.linhaencomendas = linhaencomendas;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public double getPreco() {
        return this.preco;
    }
    
    public void setPreco(double preco) {
        this.preco = preco;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getQuantidadeemstock() {
        return this.quantidadeemstock;
    }
    
    public void setQuantidadeemstock(BigDecimal quantidadeemstock) {
        this.quantidadeemstock = quantidadeemstock;
    }
    public Set getLinhavendaprodutoses() {
        return this.linhavendaprodutoses;
    }
    
    public void setLinhavendaprodutoses(Set linhavendaprodutoses) {
        this.linhavendaprodutoses = linhavendaprodutoses;
    }
    public Set getLinhaencomendas() {
        return this.linhaencomendas;
    }
    
    public void setLinhaencomendas(Set linhaencomendas) {
        this.linhaencomendas = linhaencomendas;
    }




}


