package BaseDados;
// Generated 7/jun/2017 21:44:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Servico generated by hbm2java
 */
public class Servico  implements java.io.Serializable {


     private BigDecimal codigo;
     private Funcionario funcionario;
     private Cliente cliente;
     private Tiposervico tiposervico;
     private String nome;
     private double preco;
     private Set linhavendaservicoses = new HashSet(0);

    public Servico() {
    }

	
    public Servico(BigDecimal codigo, Funcionario funcionario, Cliente cliente, Tiposervico tiposervico, String nome, double preco) {
        this.codigo = codigo;
        this.funcionario = funcionario;
        this.cliente = cliente;
        this.tiposervico = tiposervico;
        this.nome = nome;
        this.preco = preco;
    }
    public Servico(BigDecimal codigo, Funcionario funcionario, Cliente cliente, Tiposervico tiposervico, String nome, double preco, Set linhavendaservicoses) {
       this.codigo = codigo;
       this.funcionario = funcionario;
       this.cliente = cliente;
       this.tiposervico = tiposervico;
       this.nome = nome;
       this.preco = preco;
       this.linhavendaservicoses = linhavendaservicoses;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Tiposervico getTiposervico() {
        return this.tiposervico;
    }
    
    public void setTiposervico(Tiposervico tiposervico) {
        this.tiposervico = tiposervico;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public double getPreco() {
        return this.preco;
    }
    
    public void setPreco(double preco) {
        this.preco = preco;
    }
    public Set getLinhavendaservicoses() {
        return this.linhavendaservicoses;
    }
    
    public void setLinhavendaservicoses(Set linhavendaservicoses) {
        this.linhavendaservicoses = linhavendaservicoses;
    }




}


