package BaseDados;
// Generated 7/jun/2017 21:44:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tiposervico generated by hbm2java
 */
public class Tiposervico  implements java.io.Serializable {


     private BigDecimal codigo;
     private String nome;
     private Set servicos = new HashSet(0);

    public Tiposervico() {
    }

	
    public Tiposervico(BigDecimal codigo, String nome) {
        this.codigo = codigo;
        this.nome = nome;
    }
    public Tiposervico(BigDecimal codigo, String nome, Set servicos) {
       this.codigo = codigo;
       this.nome = nome;
       this.servicos = servicos;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getServicos() {
        return this.servicos;
    }
    
    public void setServicos(Set servicos) {
        this.servicos = servicos;
    }




}


