package BaseDados;
// Generated 7/jun/2017 21:44:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Vendaprodutos generated by hbm2java
 */
public class Vendaprodutos  implements java.io.Serializable {


     private BigDecimal codigo;
     private Cliente cliente;
     private double valortotal;
     private boolean pago;
     private Set linhavendaprodutoses = new HashSet(0);

    public Vendaprodutos() {
    }

	
    public Vendaprodutos(BigDecimal codigo, Cliente cliente, double valortotal, boolean pago) {
        this.codigo = codigo;
        this.cliente = cliente;
        this.valortotal = valortotal;
        this.pago = pago;
    }
    public Vendaprodutos(BigDecimal codigo, Cliente cliente, double valortotal, boolean pago, Set linhavendaprodutoses) {
       this.codigo = codigo;
       this.cliente = cliente;
       this.valortotal = valortotal;
       this.pago = pago;
       this.linhavendaprodutoses = linhavendaprodutoses;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public double getValortotal() {
        return this.valortotal;
    }
    
    public void setValortotal(double valortotal) {
        this.valortotal = valortotal;
    }
    public boolean isPago() {
        return this.pago;
    }
    
    public void setPago(boolean pago) {
        this.pago = pago;
    }
    public Set getLinhavendaprodutoses() {
        return this.linhavendaprodutoses;
    }
    
    public void setLinhavendaprodutoses(Set linhavendaprodutoses) {
        this.linhavendaprodutoses = linhavendaprodutoses;
    }




}


