package BaseDados;
// Generated 7/jun/2017 21:44:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Vendaservicos generated by hbm2java
 */
public class Vendaservicos  implements java.io.Serializable {


     private BigDecimal codigo;
     private Funcionario funcionario;
     private Cliente cliente;
     private double valortotal;
     private boolean pago;
     private Set linhavendaservicoses = new HashSet(0);

    public Vendaservicos() {
    }

	
    public Vendaservicos(BigDecimal codigo, Funcionario funcionario, Cliente cliente, double valortotal, boolean pago) {
        this.codigo = codigo;
        this.funcionario = funcionario;
        this.cliente = cliente;
        this.valortotal = valortotal;
        this.pago = pago;
    }
    public Vendaservicos(BigDecimal codigo, Funcionario funcionario, Cliente cliente, double valortotal, boolean pago, Set linhavendaservicoses) {
       this.codigo = codigo;
       this.funcionario = funcionario;
       this.cliente = cliente;
       this.valortotal = valortotal;
       this.pago = pago;
       this.linhavendaservicoses = linhavendaservicoses;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public double getValortotal() {
        return this.valortotal;
    }
    
    public void setValortotal(double valortotal) {
        this.valortotal = valortotal;
    }
    public boolean isPago() {
        return this.pago;
    }
    
    public void setPago(boolean pago) {
        this.pago = pago;
    }
    public Set getLinhavendaservicoses() {
        return this.linhavendaservicoses;
    }
    
    public void setLinhavendaservicoses(Set linhavendaservicoses) {
        this.linhavendaservicoses = linhavendaservicoses;
    }




}


